tarata
             ports:-"15000"
             
		
		
			
    wordpress:
        image:wordpress
        container_name:wordpress2
        links:
           -mariadb:mysql
        ports:
           -"15001:80"	
            
			
			
			
		
		